let menu = [
    {
        name:"电子产品",
        color:"col1",
    },
    {
        name:"智能数码",
        color:"col2"
    },
    {
        name:"手机配件",
        color:"col1"
    }
];
let menu_detail= [
    [
        {
            name:"手机",
            count:50,
            color:"labe1",
        },
        {
            name:"笔记本",
            count:34,
            color:"labe2",
        },
        {
            name:"平板",
            count:4,
            color:"labe3",
        },
        {
            name:"显示器",
            count:434,
            color:"labe4",
        },
        {
            name:"游戏",
            count:34,
            color:"labe5",
        }
    ],
    [
        {
            name:"手环",
            count:300,
            color:"labe1",
        },
        {
            name:"手表",
            count:340,
            color:"labe2",
        },
        {
            name:"VR眼镜",
            count:735,
            color:"labe3",
        }
    ],
    [
        {
            name:"耳机",
            count:456,
            color:"labe1",
        },
        {
            name:"移动电源",
            count:156,
            color:"labe2",
        },
        {
            name:"手机壳",
            count:400,
            color:"labe3",
        },
        {
            name:"数据线",
            count:89,
            color:"labe4",
        },
        {
            name:"手机支架",
            count:90,
            color:"labe5",
        },
        {
            name:"手机贴膜",
            count:567,
            color:"labe1",
        },


    ]
];